name: do_what_now
description: > 
  Result package for Dart and Flutter designed around fluent APIs and a functional approach to error handling, because things go wrong!.

version: 1.0.4
repository: https://github.com/ewilliams0305/DoWhatNow.Dart

topics:
  - railway
  - functional
  - errors
  - result
  - ensure

environment:
  sdk: ^3.0.5

dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
